### ISSUE TITLE
Requirments need updating due to not running on Raspberry Pi Zero 2 W

### ISSUE THREAD

**Issue by thommo17** [ScottSturdivant/rpi_metar#28]
G'day Scott,

I was able to get my hands on a few new raspberry pis but they must be quite a bit different than the old ones or maybe its Bullseye that's causing this but when I was installing rpi_metar on them they don't work as easily any more.

With the requirements as they are now it will cause an error when installing RPi.GPIO and fail so I changed it to 0.7.1 on my fork and got passed that error but then rpi_ws281x will say Hardware revision is not supported for rpi_ws281x.py on 4.1.0

I then tried to update that to 4.3.4 but get this in journalctl

```
Jan 18 11:43:10 Australian-METAR-Map systemd[1]: Started METAR Display.
Jan 18 11:43:11 Australian-METAR-Map rpi_metar[611]: Traceback (most recent call last):
Jan 18 11:43:11 Australian-METAR-Map rpi_metar[611]:   File "/opt/rpi_metar_au/lib/python3.9/site-packages/pkg_resources/__init__.py", line 583, in _build_master
Jan 18 11:43:11 Australian-METAR-Map rpi_metar[611]:     ws.require(__requires__)
Jan 18 11:43:11 Australian-METAR-Map rpi_metar[611]:   File "/opt/rpi_metar_au/lib/python3.9/site-packages/pkg_resources/__init__.py", line 900, in require
Jan 18 11:43:11 Australian-METAR-Map rpi_metar[611]:     needed = self.resolve(parse_requirements(requirements))
Jan 18 11:43:11 Australian-METAR-Map rpi_metar[611]:   File "/opt/rpi_metar_au/lib/python3.9/site-packages/pkg_resources/__init__.py", line 791, in resolve
Jan 18 11:43:11 Australian-METAR-Map rpi_metar[611]:     raise VersionConflict(dist, req).with_context(dependent_req)
Jan 18 11:43:11 Australian-METAR-Map rpi_metar[611]: pkg_resources.ContextualVersionConflict: (rpi-ws281x 4.3.4 (/opt/rpi_metar_au/lib/python3.9/site-packages), Requirement.parse('rpi-ws281x==4.1.0'), {'rpi-metar'})
Jan 18 11:43:11 Australian-METAR-Map rpi_metar[611]: During handling of the above exception, another exception occurred:
Jan 18 11:43:11 Australian-METAR-Map rpi_metar[611]: Traceback (most recent call last):
Jan 18 11:43:11 Australian-METAR-Map rpi_metar[611]:   File "/opt/rpi_metar_au/bin/rpi_metar", line 6, in <module>
Jan 18 11:43:11 Australian-METAR-Map rpi_metar[611]:     from pkg_resources import load_entry_point
Jan 18 11:43:11 Australian-METAR-Map rpi_metar[611]:   File "/opt/rpi_metar_au/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3252, in <module>
Jan 18 11:43:11 Australian-METAR-Map rpi_metar[611]:     def _initialize_master_working_set():
Jan 18 11:43:11 Australian-METAR-Map rpi_metar[611]:   File "/opt/rpi_metar_au/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
Jan 18 11:43:11 Australian-METAR-Map rpi_metar[611]:     f(*args, **kwargs)
Jan 18 11:43:11 Australian-METAR-Map rpi_metar[611]:   File "/opt/rpi_metar_au/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
Jan 18 11:43:11 Australian-METAR-Map rpi_metar[611]:     working_set = WorkingSet._build_master()
Jan 18 11:43:11 Australian-METAR-Map rpi_metar[611]:   File "/opt/rpi_metar_au/lib/python3.9/site-packages/pkg_resources/__init__.py", line 585, in _build_master
Jan 18 11:43:11 Australian-METAR-Map rpi_metar[611]:     return cls._build_from_requirements(__requires__)
Jan 18 11:43:11 Australian-METAR-Map rpi_metar[611]:   File "/opt/rpi_metar_au/lib/python3.9/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
Jan 18 11:43:11 Australian-METAR-Map rpi_metar[611]:     dists = ws.resolve(reqs, Environment())
Jan 18 11:43:11 Australian-METAR-Map rpi_metar[611]:   File "/opt/rpi_metar_au/lib/python3.9/site-packages/pkg_resources/__init__.py", line 786, in resolve
Jan 18 11:43:11 Australian-METAR-Map rpi_metar[611]:     raise DistributionNotFound(req, requirers)
Jan 18 11:43:11 Australian-METAR-Map rpi_metar[611]: pkg_resources.DistributionNotFound: The 'rpi-ws281x==4.1.0' distribution was not found and is required by rpi-metar
Jan 18 11:43:11 Australian-METAR-Map systemd[1]: rpi_metar_au.service: Main process exited, code=exited, status=1/FAILURE
Jan 18 11:43:11 Australian-METAR-Map systemd[1]: rpi_metar_au.service: Failed with result 'exit-code'.
Jan 18 11:43:11 Australian-METAR-Map systemd[1]: rpi_metar_au.service: Scheduled restart job, restart counter is at 5.
Jan 18 11:43:11 Australian-METAR-Map systemd[1]: Stopped METAR Display.
Jan 18 11:43:11 Australian-METAR-Map systemd[1]: rpi_metar_au.service: Start request repeated too quickly.
Jan 18 11:43:11 Australian-METAR-Map systemd[1]: rpi_metar_au.service: Failed with result 'exit-code'.
Jan 18 11:43:11 Australian-METAR-Map systemd[1]: Failed to start METAR Display.

```

I'm a bit stumped trying to figure out how to get rpi-metar to recognise the new version of rpi-ws281x

Can you please help?

**Comment by thommo17** [comment]
I was able to fix this by changing the version number in setup.py to 0.5

No idea what that does but it works haha
